feat:add `list` command to list all workspace tasks grouped by workspace
rsm-hcd/spino pull request #12
Opened 2024-11-10 12:47 UTC by allenthich

This will close [feat: add command to list all tasks](https://github.com/rsm-hcd/spino/issues/11).

### Current Behavior:
No command exists to list all the available workspace tasks

### Expected Behavior:
Run `spino list` to display all available workspace tasks

Example output:
```
@rsm-hcd/spino:
    test:        deno task test:ci --watch
    test:ci:     deno test --allow-read
```

### Related Notes/Future issues:
- [ ] Include root `deno.json` tasks (`list` and running `spino [TASK]` should include this)
- [ ] Potentially handle nested workspaces and indent them by depth level?

2024-11-12 07:23 UTC, newkdr approved these changes

2024-11-12 12:32 UTC, myty requested changes
First off, thank you for this PR!  There is one blocking change in `main.ts` that will need addressed, but overall it looks good.  If you'd like to write `main.test.ts`, that would be great, but not required.

2024-11-12 12:32 UTC, myty commented on cli/main.ts
>    Deno.exit(0);
issue: This line now prevents any task from running.  For instance, running, `deno task spino test:ci` doesn't do anything.  Removing the early exit, enables that. Ideally, there would be tests to catch this.  I'll add an issue to add some tests.
```suggestion
```

2024-11-12 12:32 UTC, myty commented on cli/command-parser.ts
> +        command: arg,
praise: nice addition with this one

2024-11-12 12:32 UTC, myty commented on cli/commands/list.ts
> +    });
suggestion (non-blocking): Consider using a `flatMap` off of `Object.entries(groupedTasks)` to accomplish the same thing.

2024-11-14 03:57 UTC, allenthich commented
@myty Thanks for taking the time to provide feedback!
I will address the comments and add a test file this weekend.

2024-11-17 07:53 UTC, allenthich commented
@myty I've added a few changes in order to test the `main.ts` entry point and its handling of executing commands.
Any feedback on the changes would very much be appreciated!

2024-12-01 18:56 UTC, myty approved these changes
@allenthich Thanks for adding the tests.  I'm going to merge this in.

2024-12-01 18:57 UTC, merged